trigger: none

pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - '.devcontainer/**'  
    - 'visuals/**'  
    - '*.md'  

schedules:
- cron: '0 23 * * *'
  displayName: 'Nightly build (UTC)'
  # Run if there are no changes
  always: 'true'
  branches:
    include:
    - main

variables:
- group: 'storage-access-ci'
- name: 'scriptDirectory'
  value: '$(Build.SourcesDirectory)/scripts'

jobs:
- job: 'azureregioninfo'
  displayName: 'Show Azure info'

  pool:
    name: '$(pool)'
    vmImage: $(vmImage)

  steps:
    - pwsh: |
        Get-Item Env:* | Sort-Object -Property Name
      displayName: 'List environment variables'

    - pwsh: |
        if ($env:SYSTEM_DEBUG -eq "true") {
          $InformationPreference = "Continue"
          $VerbosePreference = "Continue"
          $DebugPreference = "Continue"
        }
        . ./functions.ps1
        $vmMetadata = (Get-ComputeMetadata)
        Write-Host "Azure VM instance compute metadata:"
        $vmMetadata | Format-List -Property AzurePublicCloud, location, name, osType, vmId, vmSize
      displayName: 'Show Azure VM instance info'
      workingDirectory: '$(scriptDirectory)'
