parameters:
- name: deploymentRegion
  displayName: Azure Storage Deployment Region
  type: string
  default: eastus
# - name: jobsList
#   type: object
#   default:
#   - one
#   - two

name: $(Date:yyyyMMdd)$(Rev:.r)-${{ parameters.deploymentRegion }}

trigger:
  branches:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - '.devcontainer/**'  
    - 'visuals/**'  
    - '*.md'  

schedules:
- cron: '0 23 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
# - ${{ each value in parameters.jobsList }}:
#   - template: show-region-template.yml
#     parameters:
#       name: 'job${{ value }}'
#       displayName: 'Job ${{ value }}'
  - template: show-region-template.yml
    parameters:
      name: 'job1'
      displayName: 'Job 1'
      deploymentRegion: ${{ parameters.deploymentRegion }}
  - template: show-region-template.yml
    parameters:
      name: 'job2'
      displayName: 'Job 2'
      deploymentRegion: ${{ parameters.deploymentRegion }}
      # precedingJobs:
      # - job1
      precedingJob: job1
  - template: show-region-template.yml
    parameters:
      name: 'job3'
      displayName: 'Job 3'
      deploymentRegion: ${{ parameters.deploymentRegion }}
      # precedingJobs:
      # - job1
      precedingJob: job2
