parameters:
- name: jobsList
  type: object
  default:
  - one
  - two

trigger:
  branches:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - '.devcontainer/**'  
    - 'visuals/**'  
    - '*.md'  

schedules:
- cron: '0 23 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- ${{ each value in parameters.jobsList }}:
  - template: show-region-template.yml
    parameters:
      name: 'job${{ value }}'
      displayName: 'Job ${{ value }}'
