trigger: none

pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - '.devcontainer/**'  
    - 'visuals/**'  
    - '*.md'  

schedules:
- cron: '0 23 * * *'
  displayName: 'Nightly build (UTC)'
  # Run if there are no changes
  always: 'true'
  branches:
    include:
    - main

variables:
- group: 'storage-access-ci'
- name: 'scriptDirectory'
  value: '$(Build.SourcesDirectory)/scripts'

jobs:
- job: 'azureregioninfo'
  displayName: 'Show region info'

  pool:
    name: '$(pool)'
    vmImage: $(vmImage)

  steps:
    - pwsh: |
        if ((${env:system.debug} -eq "true") -or ($env:system_debug -eq "true") -or ($env:SYSTEM_DEBUG -eq "true")) {
          $InformationPreference = "Continue"
          $VerbosePreference = "Continue"
          $DebugPreference = "Continue"
        }
        ./show_azure_region.ps1
      displayName: 'Show Azure region'
      workingDirectory: '$(scriptDirectory)'

    - pwsh: |
        Get-Item Env:* | Sort-Object -Property Name
      displayName: 'List environment variables'

    - pwsh: |
        if ((${env:system.debug} -eq "true") -or ($env:system_debug -eq "true") -or ($env:SYSTEM_DEBUG -eq "true")) {
          Invoke-RestMethod -Headers @{"Metadata"="true"} -Method GET -NoProxy -Uri "http://169.254.169.254/metadata/instance?api-version=2021-02-01" -TimeoutSec 1

          if (Get-Command hostname -ErrorAction SilentlyContinue) {
            hostname
          }
          if (Get-Command hostnamectl -ErrorAction SilentlyContinue) {
            hostnamectl
          }
        }
      displayName: 'Diagnostics'
